### ISSUE TITLE
"Private-only" clause doesn't make much sense under GPLv3

### ISSUE THREAD

**Issue by event** [Ardumower/Raindancer#19]
GPLv3, in particular, states under section 10: "You may not impose any further restrictions on the exercise of the rights granted or affirmed under this License. For example, you may not impose a license fee, royalty, or other charge for exercise of rights granted under this License, and you may not initiate litigation (including a cross-claim or counterclaim in a lawsuit) alleging that any patent claim is infringed by making, using, selling, offering for sale, or importing the Program or any portion of it." 
And also under section 7: "All other non-permissive additional terms are considered “further restrictions” within the meaning of section 10. If the Program as you received it, or any part of it, contains a notice stating that it is governed by this License along with a term that is a further restriction, you may remove that term"

**Comment by kwrtz** [comment]
Thank you for the information. Will be fixed in v1.1.0
